import { Component, AfterViewInit, OnInit } from '@angular/core';
import Swal from 'sweetalert2';
import * as feather from 'feather-icons';
import { ScannerService } from '../scannerservice';

interface QrCodeRequestModel {
  id: number;
  companyId: number;
  companyName: string;
  companyEmail: string;
  requestId: string;
  noofQR: number; // ✅ FIXED name
  qrValidFrom: string;
  qrValidTill: string;
  isActive: boolean;
  createdDate: string;
  updatedDate: string;
  createdBy: number;
  updatedBy: number;
}

interface GeneratedQrItem {
  qrNo: number;
  qrText: string;
  companyId: number;
  companyName: string;
  requestId: string;
  qrValidFrom: string;
  qrValidTill: string;
}

interface QrImageModel {
  id?: number;               // Optional for new QR (auto-generated by DB)
  requestId: number;         // Foreign key to request
  qrCodeText: string;        // QR code text
  qrCodeImage?: string;      // Base64 string of QR image (optional for sending)
  isActive?: boolean;        // Active flag
  createdDate?: string;      // ISO date string
  createdBy?: string;        // Optional creator
  updatedDate?: string;      // Optional updated timestamp
  updatedBy?: string;        // Optional updater
  qrCodeImageBase64?: string; // Base64 encoded image for display
}
@Component({
  selector: 'app-qrgenerate',
  templateUrl: './qrgenerate.component.html',
  styleUrls: ['./qrgenerate.component.scss']
})
export class QRgenerateComponent implements OnInit, AfterViewInit {

  constructor(private scannersettingsService: ScannerService) {}

  requestList: any[] = [];
  generatedQrList: GeneratedQrItem[] = [];

  backendQrImage: string = '';
  backendQrText: string = '';

  qrRequest: QrCodeRequestModel = this.getEmptyModel();

  ngOnInit(): void {
    this.loadRequestDropdown();
  }

  ngAfterViewInit(): void {
    feather.replace();
  }

  // ✅ DEFAULT MODEL
  getEmptyModel(): QrCodeRequestModel {
    return {
      id: 0,
      companyId: 0,
      companyName: '',
      companyEmail: '',
      requestId: '',
      noofQR: 0,
      qrValidFrom: '',
      qrValidTill: '',
      isActive: true,
      createdDate: new Date().toISOString(),
      updatedDate: new Date().toISOString(),
      createdBy: 1,
      updatedBy: 1
    };
  }

  // ✅ LOAD DROPDOWN
  loadRequestDropdown(): void {
    this.scannersettingsService.getRequestDropdown().subscribe({
      next: (res: any) => {
        this.requestList = res?.data || res || [];
      },
      error: () => {
        Swal.fire('Error', 'Failed to load request dropdown', 'error');
      }
    });
  }

  // ✅ AUTO FILL
  onRequestChange(): void {
    const selected = this.requestList.find(x => x.requestId == this.qrRequest.requestId);

    if (selected) {
      this.qrRequest.companyId = selected.companyId;
      this.qrRequest.companyName = selected.companyName;
    }
  }

  // ✅ MAIN GENERATE FUNCTION
  generateQrCodes(): void {

    if (!this.isFormValid()) {
      Swal.fire('Validation', 'Please fill all required fields', 'warning');
      return;
    }

    // DATE VALIDATION
    const from = new Date(this.qrRequest.qrValidFrom);
    const till = new Date(this.qrRequest.qrValidTill);

    if (till < from) {
      Swal.fire('Invalid Date', 'Valid Till must be >= Valid From', 'warning');
      return;
    }

    // ✅ FIXED PAYLOAD (CRITICAL)
    const payload = {
      ...this.qrRequest,
      id: this.qrRequest.id || 0,
      noofQR: this.qrRequest.noofQR,
      createdDate: new Date().toISOString(),
      updatedDate: new Date().toISOString()
    };

    console.log('FINAL PAYLOAD:', payload);

    // ✅ BACKEND QR CALL
    this.scannersettingsService.generateQR(payload).subscribe({
      next: (res: any) => {
        this.backendQrText = res.text;
        this.backendQrImage = `data:image/png;base64,${res.imageBase64}`;
      },
      error: (err) => {
        console.error(err);
        Swal.fire('Error', 'Backend QR generation failed', 'error');
      }
    });

    // ✅ FRONTEND MULTIPLE QR
    this.generateFrontendQR();

    setTimeout(() => feather.replace(), 0);
  }

  // ✅ FRONTEND QR GENERATION
  generateFrontendQR(): void {
    const total = this.qrRequest.noofQR;

    this.generatedQrList = Array.from({ length: total }, (_, i) => ({
      qrNo: i + 1,
      companyId: this.qrRequest.companyId,
      companyName: this.qrRequest.companyName,
      requestId: this.qrRequest.requestId,
      qrValidFrom: this.qrRequest.qrValidFrom,
      qrValidTill: this.qrRequest.qrValidTill,
      qrText: JSON.stringify({
        requestId: this.qrRequest.requestId,
        companyName: this.qrRequest.companyName,
        qrNo: i + 1
      })
    }));

    Swal.fire('Success', `${total} QR code(s) generated`, 'success');
  }

  // ✅ SAVE (READY)
  saveQrRequest(): void {
    if (!this.isFormValid()) {
      Swal.fire('Validation', 'Please fill all required fields', 'warning');
      return;
    }

    console.log('SAVE PAYLOAD:', this.qrRequest);

    Swal.fire('Success', 'Ready to save', 'success');
  }

  // ✅ CLEAR
  clearForm(): void {
    this.qrRequest = this.getEmptyModel();
    this.generatedQrList = [];
    this.backendQrImage = '';
    this.backendQrText = '';
  }

  // ✅ VALIDATION
  private isFormValid(): boolean {
    return !!(
      this.qrRequest.companyId &&
      this.qrRequest.companyName.trim() &&
      this.qrRequest.requestId.trim() &&
      this.qrRequest.noofQR > 0 &&
      this.qrRequest.qrValidFrom &&
      this.qrRequest.qrValidTill
    );
  }

  sendEmail(): void {

  if (!this.backendQrImage) {
    Swal.fire('Error', 'Generate QR first', 'warning');
    return;
  }

  const payload = {
    email: this.qrRequest.companyEmail, // make sure this exists
    qrText: this.backendQrText,
    qrImageBase64: this.backendQrImage.split(',')[1] // remove data:image/png;base64
  };

  this.scannersettingsService.sendQrEmail(payload).subscribe({
    next: () => {
      Swal.fire('Success', 'Email sent successfully', 'success');
    },
    error: () => {
      Swal.fire('Error', 'Failed to send email', 'error');
    }
  });
}

}